# Generated by Django 3.1.2 on 2020-11-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandel', '0001_initial'),
        ('authenticate', '0002_auto_20201025_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='urls', to='urlhandel.short_urls'),
        ),
    ]
